package api.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.PositiveOrZero;

/**
 * The @Entity annotation specifies that the class is an entity
 * and is mapped to a database table.
 * The @Table annotation specifies the name of the database table
 * which the entity is mapped to.
 * They are annotations provided by the Java Persistence API (JPA).
 */
@Entity
@Table(name = "insureditem")
public class InsuredItem {
    /*
     * The @Id annotation specifies the primary key of an entity.
     * The @GeneratedValue annotation provides for the specification of
     * generation strategies for the values of primary keys.
     * Here we are using the GenerationType.IDENTITY strategy which
     * indicates that the primary key should be generated by the database.
     * Other strategies include GenerationType.AUTO, GenerationType.SEQUENCE,
     * which are used to generate primary keys programmatically.
     * GenerationType.AUTO allows the persistence provider to choose the
     * generation strategy.
     * A JPA provider such as Hibernate will choose an appropriate primary
     * key generation strategy based on the database dialect being used.
     * It will normally select one of the following strategies:
     * GenerationType.SEQUENCE which uses a database sequence to generate
     * primary key values or
     * GenerationType.IDENTITY for databases that support auto-increment
     * columns, e.g., H2, MySQL, SQLite, MariaDB, PostgreSQL, etc.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotNull(message = "Product type is required")
    private String productType;

    @NotNull(message = "Product value is required")
    @Min(value = 0, message = "Product value must be non-negative")
    private double productValue;

    @PositiveOrZero(message = "Quote amount must be non-negative")
    private double quoteAmount;

    // Store only the reference to customer microservice
    @Pattern(regexp = "^ACC\\d{3}$", message = "Account number must start with ACC followed by 3 digits")
    private String customerAccountNumber;

    /*
     * We need the default constructor in a Spring Boot application
     * so that the framework can instantiate the class using reflection.
     * Reflection allows Spring to inspect and manipulate classes, methods,
     * and fields at runtime. When Spring needs to create an instance of
     * a class e.g., for dependency injection, it uses the default
     * constructor to instantiate the class.
     * Without a default constructor, Spring cannot create an instance of
     * the class using reflection which is a feature in Java that allows
     * a program to inspect and manipulate its own structure and behavior
     * at runtime. This means that the program can look at its own
     * classes, methods, and fields, and even create new instances of
     * classes or call methods dynamically.
     */
    public InsuredItem() {
    }

    /*
     * We use a constructor to initialize all fields except the id field.
     * We don't have to initialize the id field because it is generated
     * by the database when a new record is inserted.
     */
    public InsuredItem(String productType, double productValue, double quoteAmount, String customerAccountNumber) {
        this.productType = productType;
        this.productValue = productValue;
        this.quoteAmount = quoteAmount;
        this.customerAccountNumber = customerAccountNumber;
    }

    /*
     * We create getter methods for all fields except the id field.
     * We don't create a setter method for the id field because the
     * id field is generated by the database when a new record is inserted.
     * Spring uses the getter methods to access the field values and it
     * uses the setter methods to set the field values.
     */

    public Long getId() {
        return id;
    }

    public String getProductType() {
        return productType;
    }

    public void setProductType(String productType) {
        this.productType = productType;
    }

    public double getProductValue() {
        return productValue;
    }

    public void setProductValue(double productValue) {
        this.productValue = productValue;
    }

    public double getQuoteAmount() {
        return quoteAmount;
    }

    public void setQuoteAmount(double quoteAmount) {
        this.quoteAmount = quoteAmount;
    }

    public String getCustomerAccountNumber() {
        return customerAccountNumber;
    }

    public void setCustomerAccountNumber(String customerAccountNumber) {
        this.customerAccountNumber = customerAccountNumber;
    }

    /*
     * We override the toString() method to return a string representation
     * of the object. Here we are using the String.format() method to
     * format the string.
     * The toString() method is not required but is useful for debugging.
     */
    @Override
    public String toString() {
        return String.format("InsuredItem[id=%d, productType='%s', " +
                "productValue='%.2f', quoteAmount='%.2f', " +
                "customerAccountNumber='%s']",
                id, productType, productValue, quoteAmount,
                customerAccountNumber);
    }

}