package api.model;

import jakarta.persistence.*;

/**
 * Customer
 * This class represents a customer entity in the database.
 * It is annotated with @Entity and @Table to specify that it is a JPA
 * entity and to specify the name of the database table.
 * The class has private fields for the customer's account number, name, and
 * email. It has a default constructor and a parameterized constructor to
 * initialize the fields. It has getter and setter methods for the fields, and
 * it overrides the toString() method
 * to return a string representation of the object.
 * The @Entity annotation specifies that the class is an entity and is
 * mapped to a database table.
 * The @Table annotation specifies the name of the database table
 * which the entity is mapped to.
 * They are annotations provided by the Java Persistence API (JPA).
 */
@Entity
@Table(name = "customer")
public class Customer {
    /*
     * The @Id annotation specifies the primary key of an entity.
     * The @GeneratedValue annotation provides for the specification of
     * generation strategies for the values of primary keys.
     * Here we are using the GenerationType.IDENTITY strategy which
     * indicates that the primary key should be generated by the database.
     * Other strategies include GenerationType.AUTO, GenerationType
     * .SEQUENCE, which are used to generate primary keys programmatically.
     * GenerationType.AUTO allows the persistence provider to choose the
     * generation strategy.
     * A JPA provider such as Hibernate will choose an appropriate primary
     * key generation strategy based on the database dialect being used.
     * It will normally select one of the following strategies
     * GenerationType.SEQUENCE which uses a database sequence to generate
     * primary key values or GenerationType.IDENTITY for databases that
     * support auto-increment
     * columns, e.g., H2, MySQL, SQLite, MariaDB, PostgreSQL, etc.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Private fields used to restrict access to the fields
    @Column(unique = true)
    private String accountNumber;
    private String name;
    private String email;

    /***************************************************************
     * We need the default constructor in a Spring Boot application
     * so that the framework can instantiate the class using reflection.
     * Reflection allows Spring to inspect and manipulate classes,
     * methods, and fields at runtime. When Spring needs to create an
     * instance of a class e.g., for dependency injection, it uses the
     * default constructor to instantiate the class.
     * Without a default constructor, Spring cannot create an instance of
     * the class using reflection.
     ***************************************************************/
    public Customer() {
    }

    /***************************************************************
     * We use a constructor to initialize all fields except the id field.
     * We don't have to initialize the id field because it is generated
     * by the database when a new record is inserted.
     ***************************************************************/
    public Customer(String accountNumber, String name, String email) {
        this.accountNumber = accountNumber;
        this.name = name;
        this.email = email;
    }

    /***************************************************************
     * We create getter methods for all fields except the id field.
     * We don't create a setter method for the id field because the
     * id field is generated by the database when a new record is inserted.
     * Spring uses the getter methods to access the field values, and it
     * uses the setter methods to set the field values.
     ***************************************************************/
    public String getAccountNumber() {
        return accountNumber;
    }

    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    /***************************************************************
     * We override the toString() method to return a string representation
     * of the object. Here we are using the String.format() method to
     * format the string.
     * The toString() method is not required but is useful for debugging.
     ***************************************************************/
    @Override
    public String toString() {
        return String.format(
                "Customer[accountNumber='%s', name='%s', email='%s']",
                accountNumber, name, email);
    }
}