package api.model;

import jakarta.persistence.*;

/**
 * The @Entity annotation marks this class as a JPA entity.
 * The @Table annotation specifies the database table name.
 * This class represents the Product table in the DB.
 */
@Entity
@Table(name = "product")
public class Product {
    /*
     * The @Id annotation specifies the primary key of an entity.
     * The @GeneratedValue annotation provides for the specification of
     * generation strategies for the values of primary keys.
     * Here we are using the GenerationType.IDENTITY strategy which
     * indicates that the primary key should be generated by the database.
     * Other strategies include GenerationType.AUTO, GenerationType
     * .SEQUENCE, which are used to generate primary keys programmatically.
     * GenerationType.AUTO allows the persistence provider to choose the
     * generation strategy.
     * A JPA provider such as Hibernate will choose an appropriate primary
     * key generation strategy based on the database dialect being used.
     * It will normally select one of the following strategies
     * GenerationType.SEQUENCE which uses a database sequence to generate
     * primary key values or GenerationType.IDENTITY for databases that
     * support auto-increment
     * columns, e.g., H2, MySQL, SQLite, MariaDB, PostgreSQL, etc.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /*
     * The @Column annotation could be used to map this field to a DB column.
     */
    private String productType;

    /*
     * The @Lob annotation marks this field as a Large Object.
     * Used for storing large text data in the DB.
     */
    @Lob
    private String productDescription;

    /*
     * We need the default constructor in a Spring Boot application
     * so that the framework can instantiate the class using reflection.
     * Reflection allows Spring to inspect and manipulate classes,
     * methods, and fields at runtime. When Spring needs to create an
     * instance of a class e.g., for dependency injection, it uses the
     * default constructor to instantiate the class.
     * Without a default constructor, Spring cannot create an instance of
     * the class using reflection.
     */
    public Product() {
    }

    /*
     * We use a constructor to initialize all fields except the id field.
     * We don't have to initialize the id field because it is generated
     * by the database when a new record is inserted.
     */
    public Product(String productType, String productDescription) {
        this.productType = productType;
        this.productDescription = productDescription;
    }

    /*
     * We create getter methods for all fields except the id field.
     * We don't create a setter method for the id field because the
     * id field is generated by the database when a new record is inserted.
     * Spring uses the getter methods to access the field values, and it
     * uses the setter methods to set the field values.
     */
    public Long getId() {
        return id;
    } // End of getId() method

    public String getProductType() {
        return productType;
    } // End of getProductType() method

    public void setProductType(String productType) {
        this.productType = productType;
    } // End of setProductType() method

    public String getProductDescription() {
        return productDescription;
    } // End of getDescription() method

    public void setProductDescription(String description) {
        this.productDescription = description;
    } // End of setDescription() method

    /*
     * Overrides the toString() method to provide a string
     * representation of the Product object.
     * Useful for debugging and logging.
     */
    @Override
    public String toString() {
        return String.format(
                "Product{id=%d, productType='%s', description='%s'}",
                id, productType, productDescription);
    } // End of toString() method

} // End of class Product